#!/bin/bash

RemInst() {
sfile=$1
fmin=$2
SouDir=$3
Resp=$4
DesDir=$5

test -d ${DesDir} || mkdir ${DesDir}

Net=`saclst knetwk f ${SouDir}/${sfile} | awk '{print $2}'`
Stn=`saclst kstnm f ${SouDir}/${sfile} | awk '{print $2}'`
Loc=`saclst khole f ${SouDir}/${sfile} | awk '{print $2}'`
Chn=`saclst kcmpnm f ${SouDir}/${sfile} | awk '{print $2}'`

rfile=RESP.${Net}.${Stn}.${Loc}.${Chn}

dt=`saclst delta f ${SouDir}/${sfile} | awk '{print $2}'`
sr=`echo ${dt} | awk '{print 1/$1}'`

f4=`echo ${sr} | awk '{print $1*0.45}'`
f3=`echo ${f4} | awk '{print $1*0.5}'`
f2=${fmin}
f1=`echo ${f2} | awk '{print $1*0.5}'`

sac 1>/dev/null << EOF
r ${SouDir}/${sfile}
rmean
rtr
taper

transfer from evalresp fname ${Resp}/${rfile} to vel freqlimit ${f1} ${f2} ${f3} ${f4}
div 1.0E+9

rmean
rtr
taper

w ${DesDir}/${Net}.${Stn}.${Loc}.${Chn}.SAC
q
EOF

}



##################################

SouDir="sac"
Resp="resp"
DesDir="sac_cor"

fmin=0.2

for sfile in ${SouDir}/*SAC
do
  sfile=`basename ${sfile}`
  RemInst ${sfile} ${fmin} ${SouDir} ${Resp} ${DesDir}
done
