#!/bin/bash

saclst kstnm f sac/*Z.?.SAC | awk '{print $2}' | sort -u > station.txt

test -d sac/trash || mkdir sac/trash

for Stn in `cat station.txt`
do
  gsac 1>/dev/null 2>/dev/null << EOF
  r sac/*${Stn}*SAC
  ppk absolute markall
  wh
  q
EOF

  echo "Data qual [1 for good: 0 for bad]"
  read flag

  test ${flag} -eq 0 && mv sac/*${Stn}*SAC sac/trash

  #break #Stn
done
